# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.36.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    
  end

  desc "Deploy a new version to the App Store"
  lane :release do |options|

    # 替换图标
    relpaceIcon(options)

    # 拉取远程代码
    git_pull(only_tags: true) 

    #递增build_number 和 version_number
    build_number = increment_build_number.to_f
    increment_version_number(
      version_number: (1.0 + build_number / 10).to_s 
    )

    # 提交版本更新
    commit_version_bump(
      message: "Version Bump",
    )
    # 将更改推送到远端
    push_to_git_remote


    # 配置证书和描述文件
    configProvision

    # 配置工程文件
    configProject(options[:appName])

    fileName = "Calculator" + get_version_number + ".ipa"

    gym(
      clean: true,
      output_directory: "./build",
      export_method: "enterprise",
      output_name: fileName
    )

  end

  def relpaceIcon(options)
    download_file(url: options[:icon120], destination_path: './Calculator/Assets.xcassets/AppIcon.appiconset/57X57.png')
    download_file(url: options[:icon180], destination_path: './Calculator/Assets.xcassets/AppIcon.appiconset/120X120.png')

    git_commit(path: ["./Calculator/Assets.xcassets/AppIcon.appiconset/57X57.png", "./Calculator/Assets.xcassets/AppIcon.appiconset/120X120.png"], message: "replace icon")

  end


  def configProject(appName)
    
    update_project_provisioning(
      profile: "./cert/InHouseText.mobileprovision", # optional if you use sigh
    )

    update_info_plist(
      plist_path: "./Calculator/Info.plist",
      display_name: appName.to_s
    )
  end

  private_lane :configProvision do 
    cert（
      output_path： "./cert"
    ）
    sigh(
      force: true,
      output_path: "./cert",
      filename: "InHouseText.mobileprovision"
    )
  end


  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded. 
# Learn more at https://github.com/fastlane/fastlane#metrics
